apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: default
  hub: istio
  tag: 1.12.1
  meshConfig:
    enablePrometheusMerge: true
    accessLogFile: /dev/stdout
    accessLogEncoding: JSON
    enableTracing: true
    defaultConfig:
      tracing:
        sampling: 100 #sampling percentage - default is 1%
        zipkin:
          address: zipkin.istio-system.svc:9411   
  components:
    ingressGateways:
    - name: istio-ingressgateway
      enabled: true
      k8s:
        hpaSpec:
            minReplicas: 1
            maxReplicas: 20
        nodeSelector:
            $NODE_SELECTOR_KEY_VALUE
        resources:
            requests:
              cpu: 10m
              memory: 40Mi
            limits:
              cpu: "1"
              memory: 1Gi
        readinessProbe:
            timeoutSeconds: 1
        service:
            type: ClusterIP
    pilot:
      k8s:
        hpaSpec:
            minReplicas: 1
            maxReplicas: 20
        nodeSelector:
            $NODE_SELECTOR_KEY_VALUE
        resources:
            requests:
              cpu: 50m
              memory: 50Mi
            limits:
              cpu: 500m
              memory: 512Mi
        readinessProbe:
            timeoutSeconds: 3